export const metadata = {
    title: 'Admin Login Next.js',
    description: 'Generated by Next.js',
}

export default function Layout({ children }) {
    return (
        <div>{children}</div>
    )
}