import styles from '../ui/dashboard/dashboard.module.css';
import Navbar from '../ui/dashboard/navbar/navbar';
import Sidebar from '../ui/dashboard/sidebar/sidebar';
import Footer from '../ui/dashboard/footer/footer';

export const metadata = {
    title: 'Admin Dashboard Next.js',
    description: 'Generated by Next.js',
}

export default function Layout({ children }) {
    return (
        <div className={styles.container}>
            <div className={styles.menu}>
                <Sidebar />
            </div>
            <div className={styles.content}>
                <Navbar />
                {children}
                <Footer />
            </div>
        </div>
    )
}